---
#
- set_fact:
    java_home_prefix: jre
    java_package_posix:
  when: java_type == "jre"

- set_fact:
    java_home_prefix: java
    java_package_posix: -devel
  when: java_type == "jdk"

- set_fact:
    package_name: openjdk-{{ java_version }}-{{ java_type }}
  when: ansible_os_family == "Debian"

- set_fact:
    package_name: java-1.{{ java_version }}.0-openjdk{{ java_package_posix }}
  when: ansible_os_family == "RedHat"

- name: install openjdk (debian)
  apt: name={{ package_name }}
  when: ansible_os_family == "Debian"

- name: install openjdk (redhat)
  yum: name={{ package_name }}
  when: ansible_os_family == "RedHat"

- set_fact:
    java_home: "/usr/lib/jvm/{{ java_home_prefix }}-1.{{ java_version }}.0-openjdk"
